# Generated by Django 5.2.6 on 2025-09-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customuser_display_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='employment_type',
        ),
    ]
