# Generated by Django 5.2.6 on 2025-09-05 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_job_employment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
